version: 2
updates:
- package-ecosystem: pip
  directory: "/requirements"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - postlund
  assignees:
  - postlund
  labels:
  - dependencies
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 3
  reviewers:
    - postlund
  assignees:
    - postlund
  labels:
    - dependencies
