image: gitpod/workspace-full
tasks:
  - name: Development
    init: ./scripts/setup_dev_env.sh
    command: source bin/activate

ports:
  - port: 4000 # Used for documentation
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - ms-python.python
