image: gitpod/workspace-full
tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
  - name: Documentation
    command: ./scripts/build_docs.sh
  - name: Development
    init: ./scripts/setup_dev_env.sh && source bin/activate; tox -p auto
    command: source bin/activate

ports:
  - port: 4000 # Used for documentation
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - ms-python.python

github:
  prebuilds:
    addBadge: true
