variables:
  code_dirs:
    - pyatv
    - tests
    - examples
    - scripts
  pydirs:
    - pyatv
    - scripts
    - examples
  cs_exclude_words: infoms,cann,cant,asai,cafs,assertIn
  requirements_file: requirements/requirements.txt
  miniaudio_package: $(grep miniaudio= requirements/requirements.txt)

dependencies:
  files:
    - "{requirements_file}"
    - requirements/requirements_docs.txt
    - requirements/requirements_test.txt

pipeline:
  pre:
    - name: clean
      run: coverage erase
    - name: fixup
      tags: [all, fixup]
      run:
        - black .
        - isort {code_dirs}
        - python scripts/api.py generate
        - python scripts/protobuf.py --download generate
  rebuild_miniaudio:
    # A lot of builds on GitHub Actions result in "Illegal Instruction"
    # when calling functions in miniaudio. Seemingly random and not
    # always. Likely has to do with some instruction set mismatch, but
    # not sure. Rebuilding miniaudio seems to improve the situation,
    # so this optional step is used by the tests workflow to do that.
    - name: miniaudio
      tags: [all, miniaudio]
      run:
        - "pip uninstall -y miniaudio"
        - "pip install --no-binary :all: {miniaudio_package}"
  validate:
    - name: pylint
      run: pylint -j 0 {pydirs}
    - name: api
      run: python scripts/api.py verify
      tags: [all, py3.8, api]
    - name: protobuf
      run: python scripts/protobuf.py --download verify
    - name: flake8
      run: flake8 --exclude=pyatv/protocols/mrp/protobuf {pydirs}
    - name: black
      run: black --fast --check .
    - name: pydocstyle
      run: pydocstyle -v --match='(?!test_).*[^pb2]\.py' {pydirs}
    - name: isort
      run: isort -c --diff {code_dirs}
    - name: cs_docs
      run: codespell -q 6 -L {cs_exclude_words} -S "lib,vendor,_site,api,assets,*~,.sass-cache,*.lock" docs
    - name: cs_code
      run: codespell -q 4 -L {cs_exclude_words} --skip="*.pyc,*.pyi,*~,tests/data" {pydirs} tests
    - name: typing
      run: mypy --python-executable "{python_executable}" --ignore-missing-imports --follow-imports=skip pyatv
    - name: pytest
      run: pytest -n auto --log-level=debug -q -d --timeout=30 --durations=10 --cov --cov-report=term-missing --cov-report=xml tests
  post:
    - name: report
      run:
        - coverage report
        - coverage html
  package:
    - name: dist
      run: python setup.py sdist bdist_wheel
      tags: [all, package]
