# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class ClientUpdatesConfigMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    artworkUpdates = ... # type: bool
    nowPlayingUpdates = ... # type: bool
    volumeUpdates = ... # type: bool
    keyboardUpdates = ... # type: bool
    outputDeviceUpdates = ... # type: bool

    def __init__(self,
        *,
        artworkUpdates : typing___Optional[bool] = None,
        nowPlayingUpdates : typing___Optional[bool] = None,
        volumeUpdates : typing___Optional[bool] = None,
        keyboardUpdates : typing___Optional[bool] = None,
        outputDeviceUpdates : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ClientUpdatesConfigMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"artworkUpdates",u"keyboardUpdates",u"nowPlayingUpdates",u"outputDeviceUpdates",u"volumeUpdates"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"artworkUpdates",u"keyboardUpdates",u"nowPlayingUpdates",u"outputDeviceUpdates",u"volumeUpdates"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"artworkUpdates",b"artworkUpdates",u"keyboardUpdates",b"keyboardUpdates",u"nowPlayingUpdates",b"nowPlayingUpdates",u"outputDeviceUpdates",b"outputDeviceUpdates",u"volumeUpdates",b"volumeUpdates"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"artworkUpdates",b"artworkUpdates",u"keyboardUpdates",b"keyboardUpdates",u"nowPlayingUpdates",b"nowPlayingUpdates",u"outputDeviceUpdates",b"outputDeviceUpdates",u"volumeUpdates",b"volumeUpdates"]) -> None: ...

clientUpdatesConfigMessage = ... # type: google___protobuf___descriptor___FieldDescriptor
