# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class NowPlayingPlayer(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    identifier: typing___Text = ...
    displayName: typing___Text = ...
    isDefaultPlayer: builtin___bool = ...

    def __init__(self,
        *,
        identifier : typing___Optional[typing___Text] = None,
        displayName : typing___Optional[typing___Text] = None,
        isDefaultPlayer : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"displayName",b"displayName",u"identifier",b"identifier",u"isDefaultPlayer",b"isDefaultPlayer"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"displayName",b"displayName",u"identifier",b"identifier",u"isDefaultPlayer",b"isDefaultPlayer"]) -> None: ...
type___NowPlayingPlayer = NowPlayingPlayer
