# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from pyatv.mrp.protobuf.ContentItem_pb2 import (
    ContentItem as pyatv___mrp___protobuf___ContentItem_pb2___ContentItem,
)

from pyatv.mrp.protobuf.PlaybackQueueContext_pb2 import (
    PlaybackQueueContext as pyatv___mrp___protobuf___PlaybackQueueContext_pb2___PlaybackQueueContext,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class PlaybackQueue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    location = ... # type: int
    requestId = ... # type: typing___Text
    sendingPlaybackQueueTransaction = ... # type: bool
    queueIdentifier = ... # type: typing___Text

    @property
    def contentItems(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[pyatv___mrp___protobuf___ContentItem_pb2___ContentItem]: ...

    @property
    def context(self) -> pyatv___mrp___protobuf___PlaybackQueueContext_pb2___PlaybackQueueContext: ...

    def __init__(self,
        *,
        location : typing___Optional[int] = None,
        contentItems : typing___Optional[typing___Iterable[pyatv___mrp___protobuf___ContentItem_pb2___ContentItem]] = None,
        context : typing___Optional[pyatv___mrp___protobuf___PlaybackQueueContext_pb2___PlaybackQueueContext] = None,
        requestId : typing___Optional[typing___Text] = None,
        sendingPlaybackQueueTransaction : typing___Optional[bool] = None,
        queueIdentifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PlaybackQueue: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"context",u"location",u"queueIdentifier",u"requestId",u"sendingPlaybackQueueTransaction"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"contentItems",u"context",u"location",u"queueIdentifier",u"requestId",u"sendingPlaybackQueueTransaction"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"context",b"context",u"location",b"location",u"queueIdentifier",b"queueIdentifier",u"requestId",b"requestId",u"sendingPlaybackQueueTransaction",b"sendingPlaybackQueueTransaction"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"contentItems",b"contentItems",u"context",b"context",u"location",b"location",u"queueIdentifier",b"queueIdentifier",u"requestId",b"requestId",u"sendingPlaybackQueueTransaction",b"sendingPlaybackQueueTransaction"]) -> None: ...
