# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class RegisterVoiceInputDeviceResponseMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    deviceID = ... # type: builtin___int
    errorCode = ... # type: builtin___int

    def __init__(self,
        *,
        deviceID : typing___Optional[builtin___int] = None,
        errorCode : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> RegisterVoiceInputDeviceResponseMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"deviceID",u"errorCode"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"deviceID",u"errorCode"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"deviceID",b"deviceID",u"errorCode",b"errorCode"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"deviceID",b"deviceID",u"errorCode",b"errorCode"]) -> None: ...

registerVoiceInputDeviceResponseMessage = ... # type: google___protobuf___descriptor___FieldDescriptor
