"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class RegisterForGameControllerEventsMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class InputModeFlags(metaclass=_InputModeFlags):
        V = typing.NewType('V', builtins.int)

    Motion = RegisterForGameControllerEventsMessage.InputModeFlags.V(1)
    Buttons = RegisterForGameControllerEventsMessage.InputModeFlags.V(2)
    Digitizer = RegisterForGameControllerEventsMessage.InputModeFlags.V(3)

    class _InputModeFlags(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[InputModeFlags.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        Motion = RegisterForGameControllerEventsMessage.InputModeFlags.V(1)
        Buttons = RegisterForGameControllerEventsMessage.InputModeFlags.V(2)
        Digitizer = RegisterForGameControllerEventsMessage.InputModeFlags.V(3)

    INPUTMODEFLAGS_FIELD_NUMBER: builtins.int
    inputModeFlags: global___RegisterForGameControllerEventsMessage.InputModeFlags.V = ...

    def __init__(self,
        *,
        inputModeFlags : typing.Optional[global___RegisterForGameControllerEventsMessage.InputModeFlags.V] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"inputModeFlags",b"inputModeFlags"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"inputModeFlags",b"inputModeFlags"]) -> None: ...
global___RegisterForGameControllerEventsMessage = RegisterForGameControllerEventsMessage

registerForGameControllerEventsMessage: google.protobuf.descriptor.FieldDescriptor = ...
