# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from pyatv.mrp.protobuf.VoiceInputDeviceDescriptorMessage_pb2 import (
    VoiceInputDeviceDescriptor as pyatv___mrp___protobuf___VoiceInputDeviceDescriptorMessage_pb2___VoiceInputDeviceDescriptor,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class RegisterVoiceInputDeviceMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def deviceDescriptor(self) -> pyatv___mrp___protobuf___VoiceInputDeviceDescriptorMessage_pb2___VoiceInputDeviceDescriptor: ...

    def __init__(self,
        *,
        deviceDescriptor : typing___Optional[pyatv___mrp___protobuf___VoiceInputDeviceDescriptorMessage_pb2___VoiceInputDeviceDescriptor] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> RegisterVoiceInputDeviceMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"deviceDescriptor"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"deviceDescriptor"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"deviceDescriptor",b"deviceDescriptor"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"deviceDescriptor",b"deviceDescriptor"]) -> None: ...

registerVoiceInputDeviceMessage = ... # type: google___protobuf___descriptor___FieldDescriptor
