# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from pyatv.mrp.protobuf.SupportedCommands_pb2 import (
    SupportedCommands as pyatv___mrp___protobuf___SupportedCommands_pb2___SupportedCommands,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class SetDefaultSupportedCommandsMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    displayID = ... # type: typing___Text

    @property
    def supportedCommands(self) -> pyatv___mrp___protobuf___SupportedCommands_pb2___SupportedCommands: ...

    def __init__(self,
        *,
        supportedCommands : typing___Optional[pyatv___mrp___protobuf___SupportedCommands_pb2___SupportedCommands] = None,
        displayID : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> SetDefaultSupportedCommandsMessage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"displayID",u"supportedCommands"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"displayID",u"supportedCommands"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"displayID",b"displayID",u"supportedCommands",b"supportedCommands"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"displayID",b"displayID",u"supportedCommands",b"supportedCommands"]) -> None: ...

setDefaultSupportedCommandsMessage = ... # type: google___protobuf___descriptor___FieldDescriptor
