# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from pyatv.mrp.protobuf.PlayerPath_pb2 import (
    PlayerPath as pyatv___mrp___protobuf___PlayerPath_pb2___PlayerPath,
)

from pyatv.mrp.protobuf.TransactionPackets_pb2 import (
    TransactionPackets as pyatv___mrp___protobuf___TransactionPackets_pb2___TransactionPackets,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class TransactionMessage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: builtin___int = ...

    @property
    def packets(self) -> pyatv___mrp___protobuf___TransactionPackets_pb2___TransactionPackets: ...

    @property
    def playerPath(self) -> pyatv___mrp___protobuf___PlayerPath_pb2___PlayerPath: ...

    def __init__(self,
        *,
        name : typing___Optional[builtin___int] = None,
        packets : typing___Optional[pyatv___mrp___protobuf___TransactionPackets_pb2___TransactionPackets] = None,
        playerPath : typing___Optional[pyatv___mrp___protobuf___PlayerPath_pb2___PlayerPath] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"name",b"name",u"packets",b"packets",u"playerPath",b"playerPath"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"packets",b"packets",u"playerPath",b"playerPath"]) -> None: ...
type___TransactionMessage = TransactionMessage

transactionMessage: google___protobuf___descriptor___FieldDescriptor = ...
