# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class TransactionKey(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    identifier = ... # type: typing___Text
    userData = ... # type: builtin___bytes

    def __init__(self,
        *,
        identifier : typing___Optional[typing___Text] = None,
        userData : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> TransactionKey: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"identifier",u"userData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"identifier",u"userData"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"identifier",b"identifier",u"userData",b"userData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"identifier",b"identifier",u"userData",b"userData"]) -> None: ...
