name: Question or support
description: If you are using `pyatv` and have questions regarding how to use it in any way (e.g. development), use this template.
labels: [question]
body:
  - type: textarea
    id: question-support
    attributes:
      label: What do you need help with?
      description: Please enter your question below. Make sure to include software versions, error logs, etc. when applicable. The more information you provide, the easier it will be to help.
    validations:
      required: true
