version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "postlund"
    default_labels:
      - "dependencies"
    default_assignees:
      - "postlund"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
