"""Constants used in the public API."""

from enum import Enum


MAJOR_VERSION = "0"
MINOR_VERSION = "4"
PATCH_VERSION = "1a1"
__short_version__ = "{}.{}".format(MAJOR_VERSION, MINOR_VERSION)
__version__ = "{}.{}".format(__short_version__, PATCH_VERSION)


class Protocol(Enum):
    """All supported protocol."""

    DMAP = 1
    MRP = 2
    AirPlay = 3


class MediaType(Enum):
    """All suuported media types."""

    Unknown = 0
    Video = 1
    Music = 2
    TV = 3


class DeviceState(Enum):
    """All supported device states."""

    Idle = 0
    Loading = 1
    Paused = 2
    Playing = 3
    Stopped = 4
    Seeking = 5


class RepeatState(Enum):
    """All supported repeat states."""

    Off = 0
    Track = 1
    All = 2


class ShuffleState(Enum):
    """All supported shuffle states."""

    Off = 0
    Albums = 1
    Songs = 2


class PowerState(Enum):
    """All supported power states."""

    Unknown = 0
    Off = 1
    On = 2


class OperatingSystem(Enum):
    """Operating system on device."""

    Unknown = 0
    Legacy = 1  # Pre-tvOS (Apple TV Software)
    TvOS = 2


class DeviceModel(Enum):
    """Hardware device models."""

    Unknown = 0
    Gen2 = 1
    Gen3 = 2
    Gen4 = 3
    Gen4K = 4


class FeatureState(Enum):
    """State of a particular feature."""

    # Feature is supported by device but it is not known if it is available or not
    Unknown = 0

    # Device does not support this feature
    Unsupported = 1

    # Feature is supported by device but not available now (e.g. "pause" is
    # unavailable if nothing is playing)
    Unavailable = 2

    # Feature is supported and available
    Available = 3


# This enum is generated by scripts/features.py
class FeatureName(Enum):
    """All supported features."""

    Up = 0
    Down = 1
    Left = 2
    Right = 3
    Play = 4
    PlayPause = 5
    Pause = 6
    Stop = 7
    Next = 8
    Previous = 9
    Select = 10
    Menu = 11
    VolumeUp = 12
    VolumeDown = 13
    Home = 14
    HomeHold = 15
    TopMenu = 16
    Suspend = 17
    WakeUp = 18
    SetPosition = 19
    SetShuffle = 20
    SetRepeat = 21
    Title = 22
    Artist = 23
    Album = 24
    Genre = 25
    TotalTime = 26
    Position = 27
    Shuffle = 28
    Repeat = 29
    Artwork = 30
    PlayUrl = 31
    PowerState = 32
    TurnOn = 33
    TurnOff = 34
