"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.extension_dict
import google.protobuf.message
import pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ClientUpdatesConfigMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARTWORKUPDATES_FIELD_NUMBER: builtins.int
    NOWPLAYINGUPDATES_FIELD_NUMBER: builtins.int
    VOLUMEUPDATES_FIELD_NUMBER: builtins.int
    KEYBOARDUPDATES_FIELD_NUMBER: builtins.int
    OUTPUTDEVICEUPDATES_FIELD_NUMBER: builtins.int
    artworkUpdates: builtins.bool
    nowPlayingUpdates: builtins.bool
    volumeUpdates: builtins.bool
    keyboardUpdates: builtins.bool
    outputDeviceUpdates: builtins.bool
    def __init__(
        self,
        *,
        artworkUpdates: builtins.bool | None = ...,
        nowPlayingUpdates: builtins.bool | None = ...,
        volumeUpdates: builtins.bool | None = ...,
        keyboardUpdates: builtins.bool | None = ...,
        outputDeviceUpdates: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["artworkUpdates", b"artworkUpdates", "keyboardUpdates", b"keyboardUpdates", "nowPlayingUpdates", b"nowPlayingUpdates", "outputDeviceUpdates", b"outputDeviceUpdates", "volumeUpdates", b"volumeUpdates"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artworkUpdates", b"artworkUpdates", "keyboardUpdates", b"keyboardUpdates", "nowPlayingUpdates", b"nowPlayingUpdates", "outputDeviceUpdates", b"outputDeviceUpdates", "volumeUpdates", b"volumeUpdates"]) -> None: ...

global___ClientUpdatesConfigMessage = ClientUpdatesConfigMessage

CLIENTUPDATESCONFIGMESSAGE_FIELD_NUMBER: builtins.int
clientUpdatesConfigMessage: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2.ProtocolMessage, global___ClientUpdatesConfigMessage]
