"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class KeyboardState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        pass
    class _Enum:
        V = typing.NewType('V', builtins.int)
    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Enum.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        Unknown = KeyboardState.Enum.V(0)
        NotEditing = KeyboardState.Enum.V(1)
        DidBeginEditing = KeyboardState.Enum.V(2)
        Editing = KeyboardState.Enum.V(3)
        TextDidChange = KeyboardState.Enum.V(4)
        DidEndEditing = KeyboardState.Enum.V(5)
        Response = KeyboardState.Enum.V(6)

    Unknown = KeyboardState.Enum.V(0)
    NotEditing = KeyboardState.Enum.V(1)
    DidBeginEditing = KeyboardState.Enum.V(2)
    Editing = KeyboardState.Enum.V(3)
    TextDidChange = KeyboardState.Enum.V(4)
    DidEndEditing = KeyboardState.Enum.V(5)
    Response = KeyboardState.Enum.V(6)

    def __init__(self,
        ) -> None: ...
global___KeyboardState = KeyboardState

class AutocapitalizationType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        pass
    class _Enum:
        V = typing.NewType('V', builtins.int)
    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Enum.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        Words = AutocapitalizationType.Enum.V(1)
        Sentences = AutocapitalizationType.Enum.V(2)
        AllCharacters = AutocapitalizationType.Enum.V(3)

    Words = AutocapitalizationType.Enum.V(1)
    Sentences = AutocapitalizationType.Enum.V(2)
    AllCharacters = AutocapitalizationType.Enum.V(3)

    def __init__(self,
        ) -> None: ...
global___AutocapitalizationType = AutocapitalizationType

class KeyboardType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        pass
    class _Enum:
        V = typing.NewType('V', builtins.int)
    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Enum.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        Default = KeyboardType.Enum.V(0)
        ASCII_Capable = KeyboardType.Enum.V(1)
        NumbersAndPunctuation = KeyboardType.Enum.V(2)
        URL = KeyboardType.Enum.V(3)
        NumberPad = KeyboardType.Enum.V(4)
        PhonePad = KeyboardType.Enum.V(5)
        NamePhonePad = KeyboardType.Enum.V(6)
        EmailAddress = KeyboardType.Enum.V(7)
        DecimalPad = KeyboardType.Enum.V(8)
        Twitter = KeyboardType.Enum.V(9)
        WebSearch = KeyboardType.Enum.V(10)
        Alphanet = KeyboardType.Enum.V(11)
        PasscodePad = KeyboardType.Enum.V(12)

    Default = KeyboardType.Enum.V(0)
    ASCII_Capable = KeyboardType.Enum.V(1)
    NumbersAndPunctuation = KeyboardType.Enum.V(2)
    URL = KeyboardType.Enum.V(3)
    NumberPad = KeyboardType.Enum.V(4)
    PhonePad = KeyboardType.Enum.V(5)
    NamePhonePad = KeyboardType.Enum.V(6)
    EmailAddress = KeyboardType.Enum.V(7)
    DecimalPad = KeyboardType.Enum.V(8)
    Twitter = KeyboardType.Enum.V(9)
    WebSearch = KeyboardType.Enum.V(10)
    Alphanet = KeyboardType.Enum.V(11)
    PasscodePad = KeyboardType.Enum.V(12)

    def __init__(self,
        ) -> None: ...
global___KeyboardType = KeyboardType

class ReturnKeyType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        pass
    class _Enum:
        V = typing.NewType('V', builtins.int)
    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Enum.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        Default = ReturnKeyType.Enum.V(0)
        Go = ReturnKeyType.Enum.V(1)
        Google = ReturnKeyType.Enum.V(2)
        Join = ReturnKeyType.Enum.V(3)
        Next = ReturnKeyType.Enum.V(4)
        Route = ReturnKeyType.Enum.V(5)
        Search = ReturnKeyType.Enum.V(6)
        Send = ReturnKeyType.Enum.V(7)
        Yahoo = ReturnKeyType.Enum.V(8)
        Done = ReturnKeyType.Enum.V(9)
        EmergencyCall = ReturnKeyType.Enum.V(10)
        Continue = ReturnKeyType.Enum.V(11)

    Default = ReturnKeyType.Enum.V(0)
    Go = ReturnKeyType.Enum.V(1)
    Google = ReturnKeyType.Enum.V(2)
    Join = ReturnKeyType.Enum.V(3)
    Next = ReturnKeyType.Enum.V(4)
    Route = ReturnKeyType.Enum.V(5)
    Search = ReturnKeyType.Enum.V(6)
    Send = ReturnKeyType.Enum.V(7)
    Yahoo = ReturnKeyType.Enum.V(8)
    Done = ReturnKeyType.Enum.V(9)
    EmergencyCall = ReturnKeyType.Enum.V(10)
    Continue = ReturnKeyType.Enum.V(11)

    def __init__(self,
        ) -> None: ...
global___ReturnKeyType = ReturnKeyType

class TextInputTraits(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTOCAPITALIZATIONTYPE_FIELD_NUMBER: builtins.int
    KEYBOARDTYPE_FIELD_NUMBER: builtins.int
    RETURNKEYTYPE_FIELD_NUMBER: builtins.int
    AUTOCORRECTION_FIELD_NUMBER: builtins.int
    SPELLCHECKING_FIELD_NUMBER: builtins.int
    ENABLESRETURNKEYAUTOMATICALLY_FIELD_NUMBER: builtins.int
    SECURETEXTENTRY_FIELD_NUMBER: builtins.int
    VALIDTEXTRANGELOCATION_FIELD_NUMBER: builtins.int
    VALIDTEXTRANGELENGTH_FIELD_NUMBER: builtins.int
    PINENTRYSEPARATORINDEXES_FIELD_NUMBER: builtins.int
    autocapitalizationType: global___AutocapitalizationType.Enum.V = ...
    keyboardType: global___KeyboardType.Enum.V = ...
    returnKeyType: global___ReturnKeyType.Enum.V = ...
    autocorrection: builtins.bool = ...
    spellchecking: builtins.bool = ...
    enablesReturnKeyAutomatically: builtins.bool = ...
    secureTextEntry: builtins.bool = ...
    validTextRangeLocation: builtins.int = ...
    validTextRangeLength: builtins.int = ...
    @property
    def pINEntrySeparatorIndexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        autocapitalizationType : typing.Optional[global___AutocapitalizationType.Enum.V] = ...,
        keyboardType : typing.Optional[global___KeyboardType.Enum.V] = ...,
        returnKeyType : typing.Optional[global___ReturnKeyType.Enum.V] = ...,
        autocorrection : typing.Optional[builtins.bool] = ...,
        spellchecking : typing.Optional[builtins.bool] = ...,
        enablesReturnKeyAutomatically : typing.Optional[builtins.bool] = ...,
        secureTextEntry : typing.Optional[builtins.bool] = ...,
        validTextRangeLocation : typing.Optional[builtins.int] = ...,
        validTextRangeLength : typing.Optional[builtins.int] = ...,
        pINEntrySeparatorIndexes : typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"autocapitalizationType",b"autocapitalizationType",u"autocorrection",b"autocorrection",u"enablesReturnKeyAutomatically",b"enablesReturnKeyAutomatically",u"keyboardType",b"keyboardType",u"returnKeyType",b"returnKeyType",u"secureTextEntry",b"secureTextEntry",u"spellchecking",b"spellchecking",u"validTextRangeLength",b"validTextRangeLength",u"validTextRangeLocation",b"validTextRangeLocation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"autocapitalizationType",b"autocapitalizationType",u"autocorrection",b"autocorrection",u"enablesReturnKeyAutomatically",b"enablesReturnKeyAutomatically",u"keyboardType",b"keyboardType",u"pINEntrySeparatorIndexes",b"pINEntrySeparatorIndexes",u"returnKeyType",b"returnKeyType",u"secureTextEntry",b"secureTextEntry",u"spellchecking",b"spellchecking",u"validTextRangeLength",b"validTextRangeLength",u"validTextRangeLocation",b"validTextRangeLocation"]) -> None: ...
global___TextInputTraits = TextInputTraits

class TextEditingAttributes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TITLE_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    INPUTTRAITS_FIELD_NUMBER: builtins.int
    title: typing.Text = ...
    prompt: typing.Text = ...
    @property
    def inputTraits(self) -> global___TextInputTraits: ...
    def __init__(self,
        *,
        title : typing.Optional[typing.Text] = ...,
        prompt : typing.Optional[typing.Text] = ...,
        inputTraits : typing.Optional[global___TextInputTraits] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"inputTraits",b"inputTraits",u"prompt",b"prompt",u"title",b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"inputTraits",b"inputTraits",u"prompt",b"prompt",u"title",b"title"]) -> None: ...
global___TextEditingAttributes = TextEditingAttributes

class KeyboardMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATE_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    ENCRYPTEDTEXTCYPHERTEXT_FIELD_NUMBER: builtins.int
    state: global___KeyboardState.Enum.V = ...
    @property
    def attributes(self) -> global___TextEditingAttributes: ...
    encryptedTextCyphertext: builtins.bytes = ...
    def __init__(self,
        *,
        state : typing.Optional[global___KeyboardState.Enum.V] = ...,
        attributes : typing.Optional[global___TextEditingAttributes] = ...,
        encryptedTextCyphertext : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"encryptedTextCyphertext",b"encryptedTextCyphertext",u"state",b"state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"attributes",b"attributes",u"encryptedTextCyphertext",b"encryptedTextCyphertext",u"state",b"state"]) -> None: ...
global___KeyboardMessage = KeyboardMessage

keyboardMessage: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2.ProtocolMessage, global___KeyboardMessage] = ...
