"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ModifyOutputContextRequestType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Enum:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _EnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ModifyOutputContextRequestType._Enum.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SharedAudioPresentation: ModifyOutputContextRequestType._Enum.ValueType  # 1
    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        pass

    SharedAudioPresentation: ModifyOutputContextRequestType.Enum.ValueType  # 1

    def __init__(self,
        ) -> None: ...
global___ModifyOutputContextRequestType = ModifyOutputContextRequestType

class ModifyOutputContextRequestMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    ADDINGDEVICES_FIELD_NUMBER: builtins.int
    REMOVINGDEVICES_FIELD_NUMBER: builtins.int
    SETTINGDEVICES_FIELD_NUMBER: builtins.int
    CLUSTERAWAREADDINGDEVICES_FIELD_NUMBER: builtins.int
    CLUSTERAWAREREMOVINGDEVICES_FIELD_NUMBER: builtins.int
    CLUSTERAWARESETTINGDEVICES_FIELD_NUMBER: builtins.int
    type: global___ModifyOutputContextRequestType.Enum.ValueType
    @property
    def addingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def removingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def settingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def clusterAwareAddingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def clusterAwareRemovingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def clusterAwareSettingDevices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        type: typing.Optional[global___ModifyOutputContextRequestType.Enum.ValueType] = ...,
        addingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        removingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        settingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        clusterAwareAddingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        clusterAwareRemovingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        clusterAwareSettingDevices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addingDevices",b"addingDevices","clusterAwareAddingDevices",b"clusterAwareAddingDevices","clusterAwareRemovingDevices",b"clusterAwareRemovingDevices","clusterAwareSettingDevices",b"clusterAwareSettingDevices","removingDevices",b"removingDevices","settingDevices",b"settingDevices","type",b"type"]) -> None: ...
global___ModifyOutputContextRequestMessage = ModifyOutputContextRequestMessage

MODIFYOUTPUTCONTEXTREQUESTMESSAGE_FIELD_NUMBER: builtins.int
modifyOutputContextRequestMessage: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[pyatv.protocols.mrp.protobuf.ProtocolMessage_pb2.ProtocolMessage, global___ModifyOutputContextRequestMessage]
