"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class PlaybackQueueCapabilities(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REQUESTBYRANGE_FIELD_NUMBER: builtins.int
    REQUESTBYIDENTIFIERS_FIELD_NUMBER: builtins.int
    REQUESTBYREQUEST_FIELD_NUMBER: builtins.int
    requestByRange: builtins.bool = ...
    requestByIdentifiers: builtins.bool = ...
    requestByRequest: builtins.bool = ...
    def __init__(self,
        *,
        requestByRange : typing.Optional[builtins.bool] = ...,
        requestByIdentifiers : typing.Optional[builtins.bool] = ...,
        requestByRequest : typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"requestByIdentifiers",b"requestByIdentifiers",u"requestByRange",b"requestByRange",u"requestByRequest",b"requestByRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"requestByIdentifiers",b"requestByIdentifiers",u"requestByRange",b"requestByRange",u"requestByRequest",b"requestByRequest"]) -> None: ...
global___PlaybackQueueCapabilities = PlaybackQueueCapabilities
