"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as _ProtocolMessage_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RemoteTextInputMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.float
    version: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        timestamp: _builtins.float | None = ...,
        version: _builtins.int | None = ...,
        data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "timestamp", b"timestamp", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "timestamp", b"timestamp", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoteTextInputMessage: _TypeAlias = RemoteTextInputMessage  # noqa: Y015

REMOTETEXTINPUTMESSAGE_FIELD_NUMBER: _builtins.int
remoteTextInputMessage: _extension_dict._ExtensionFieldDescriptor[_ProtocolMessage_pb2.ProtocolMessage, Global___RemoteTextInputMessage]
