# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/protocols/mrp/protobuf/SetConnectionStateMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<pyatv/protocols/mrp/protobuf/SetConnectionStateMessage.proto\x1a\x32pyatv/protocols/mrp/protobuf/ProtocolMessage.proto\"\xa4\x01\n\x19SetConnectionStateMessage\x12\x39\n\x05state\x18\x01 \x01(\x0e\x32*.SetConnectionStateMessage.ConnectionState\"L\n\x0f\x43onnectionState\x12\x08\n\x04None\x10\x00\x12\x0e\n\nConnecting\x10\x01\x12\r\n\tConnected\x10\x02\x12\x10\n\x0c\x44isconnected\x10\x03:O\n\x19setConnectionStateMessage\x12\x10.ProtocolMessage\x18* \x01(\x0b\x32\x1a.SetConnectionStateMessage')


SETCONNECTIONSTATEMESSAGE_FIELD_NUMBER = 42
setConnectionStateMessage = DESCRIPTOR.extensions_by_name['setConnectionStateMessage']

_SETCONNECTIONSTATEMESSAGE = DESCRIPTOR.message_types_by_name['SetConnectionStateMessage']
_SETCONNECTIONSTATEMESSAGE_CONNECTIONSTATE = _SETCONNECTIONSTATEMESSAGE.enum_types_by_name['ConnectionState']
SetConnectionStateMessage = _reflection.GeneratedProtocolMessageType('SetConnectionStateMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETCONNECTIONSTATEMESSAGE,
  '__module__' : 'pyatv.protocols.mrp.protobuf.SetConnectionStateMessage_pb2'
  # @@protoc_insertion_point(class_scope:SetConnectionStateMessage)
  })
_sym_db.RegisterMessage(SetConnectionStateMessage)

if _descriptor._USE_C_DESCRIPTORS == False:
  pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(setConnectionStateMessage)

  DESCRIPTOR._options = None
  _SETCONNECTIONSTATEMESSAGE._serialized_start=117
  _SETCONNECTIONSTATEMESSAGE._serialized_end=281
  _SETCONNECTIONSTATEMESSAGE_CONNECTIONSTATE._serialized_start=205
  _SETCONNECTIONSTATEMESSAGE_CONNECTIONSTATE._serialized_end=281
# @@protoc_insertion_point(module_scope)
