"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
from pyatv.protocols.mrp.protobuf import Common_pb2 as _Common_pb2
from pyatv.protocols.mrp.protobuf import NowPlayingInfo_pb2 as _NowPlayingInfo_pb2
from pyatv.protocols.mrp.protobuf import PlaybackQueueCapabilities_pb2 as _PlaybackQueueCapabilities_pb2
from pyatv.protocols.mrp.protobuf import PlaybackQueueRequestMessage_pb2 as _PlaybackQueueRequestMessage_pb2
from pyatv.protocols.mrp.protobuf import PlaybackQueue_pb2 as _PlaybackQueue_pb2
from pyatv.protocols.mrp.protobuf import PlayerPath_pb2 as _PlayerPath_pb2
from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as _ProtocolMessage_pb2
from pyatv.protocols.mrp.protobuf import SupportedCommands_pb2 as _SupportedCommands_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetDefaultSupportedCommandsMessage(_message.Message):
    """Seems to be the same as SetStateMessage"""

    DESCRIPTOR: _descriptor.Descriptor

    NOWPLAYINGINFO_FIELD_NUMBER: _builtins.int
    SUPPORTEDCOMMANDS_FIELD_NUMBER: _builtins.int
    PLAYBACKQUEUE_FIELD_NUMBER: _builtins.int
    DISPLAYID_FIELD_NUMBER: _builtins.int
    DISPLAYNAME_FIELD_NUMBER: _builtins.int
    PLAYBACKSTATE_FIELD_NUMBER: _builtins.int
    PLAYBACKQUEUECAPABILITIES_FIELD_NUMBER: _builtins.int
    PLAYERPATH_FIELD_NUMBER: _builtins.int
    REQUEST_FIELD_NUMBER: _builtins.int
    PLAYBACKSTATETIMESTAMP_FIELD_NUMBER: _builtins.int
    displayID: _builtins.str
    displayName: _builtins.str
    playbackState: _Common_pb2.PlaybackState.Enum.ValueType
    playbackStateTimestamp: _builtins.float
    @_builtins.property
    def nowPlayingInfo(self) -> _NowPlayingInfo_pb2.NowPlayingInfo: ...
    @_builtins.property
    def supportedCommands(self) -> _SupportedCommands_pb2.SupportedCommands: ...
    @_builtins.property
    def playbackQueue(self) -> _PlaybackQueue_pb2.PlaybackQueue: ...
    @_builtins.property
    def playbackQueueCapabilities(self) -> _PlaybackQueueCapabilities_pb2.PlaybackQueueCapabilities: ...
    @_builtins.property
    def playerPath(self) -> _PlayerPath_pb2.PlayerPath: ...
    @_builtins.property
    def request(self) -> _PlaybackQueueRequestMessage_pb2.PlaybackQueueRequestMessage: ...
    def __init__(
        self,
        *,
        nowPlayingInfo: _NowPlayingInfo_pb2.NowPlayingInfo | None = ...,
        supportedCommands: _SupportedCommands_pb2.SupportedCommands | None = ...,
        playbackQueue: _PlaybackQueue_pb2.PlaybackQueue | None = ...,
        displayID: _builtins.str | None = ...,
        displayName: _builtins.str | None = ...,
        playbackState: _Common_pb2.PlaybackState.Enum.ValueType | None = ...,
        playbackQueueCapabilities: _PlaybackQueueCapabilities_pb2.PlaybackQueueCapabilities | None = ...,
        playerPath: _PlayerPath_pb2.PlayerPath | None = ...,
        request: _PlaybackQueueRequestMessage_pb2.PlaybackQueueRequestMessage | None = ...,
        playbackStateTimestamp: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["displayID", b"displayID", "displayName", b"displayName", "nowPlayingInfo", b"nowPlayingInfo", "playbackQueue", b"playbackQueue", "playbackQueueCapabilities", b"playbackQueueCapabilities", "playbackState", b"playbackState", "playbackStateTimestamp", b"playbackStateTimestamp", "playerPath", b"playerPath", "request", b"request", "supportedCommands", b"supportedCommands"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["displayID", b"displayID", "displayName", b"displayName", "nowPlayingInfo", b"nowPlayingInfo", "playbackQueue", b"playbackQueue", "playbackQueueCapabilities", b"playbackQueueCapabilities", "playbackState", b"playbackState", "playbackStateTimestamp", b"playbackStateTimestamp", "playerPath", b"playerPath", "request", b"request", "supportedCommands", b"supportedCommands"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetDefaultSupportedCommandsMessage: _TypeAlias = SetDefaultSupportedCommandsMessage  # noqa: Y015

SETDEFAULTSUPPORTEDCOMMANDSMESSAGE_FIELD_NUMBER: _builtins.int
setDefaultSupportedCommandsMessage: _extension_dict._ExtensionFieldDescriptor[_ProtocolMessage_pb2.ProtocolMessage, Global___SetDefaultSupportedCommandsMessage]
