"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
from pyatv.protocols.mrp.protobuf import PlayerPath_pb2 as _PlayerPath_pb2
from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as _ProtocolMessage_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SetNowPlayingPlayerMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLAYERPATH_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def playerPath(self) -> _PlayerPath_pb2.PlayerPath: ...
    def __init__(
        self,
        *,
        playerPath: _PlayerPath_pb2.PlayerPath | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["playerPath", b"playerPath"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["playerPath", b"playerPath"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetNowPlayingPlayerMessage: _TypeAlias = SetNowPlayingPlayerMessage  # noqa: Y015

SETNOWPLAYINGPLAYERMESSAGE_FIELD_NUMBER: _builtins.int
setNowPlayingPlayerMessage: _extension_dict._ExtensionFieldDescriptor[_ProtocolMessage_pb2.ProtocolMessage, Global___SetNowPlayingPlayerMessage]
