# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/protocols/mrp/protobuf/SetVolumeMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3pyatv/protocols/mrp/protobuf/SetVolumeMessage.proto\x1a\x32pyatv/protocols/mrp/protobuf/ProtocolMessage.proto\";\n\x10SetVolumeMessage\x12\x0e\n\x06volume\x18\x01 \x01(\x02\x12\x17\n\x0foutputDeviceUID\x18\x02 \x01(\t:=\n\x10setVolumeMessage\x12\x10.ProtocolMessage\x18\x37 \x01(\x0b\x32\x11.SetVolumeMessage')


SETVOLUMEMESSAGE_FIELD_NUMBER = 55
setVolumeMessage = DESCRIPTOR.extensions_by_name['setVolumeMessage']

_SETVOLUMEMESSAGE = DESCRIPTOR.message_types_by_name['SetVolumeMessage']
SetVolumeMessage = _reflection.GeneratedProtocolMessageType('SetVolumeMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETVOLUMEMESSAGE,
  '__module__' : 'pyatv.protocols.mrp.protobuf.SetVolumeMessage_pb2'
  # @@protoc_insertion_point(class_scope:SetVolumeMessage)
  })
_sym_db.RegisterMessage(SetVolumeMessage)

if _descriptor._USE_C_DESCRIPTORS == False:
  pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_ProtocolMessage__pb2.ProtocolMessage.RegisterExtension(setVolumeMessage)

  DESCRIPTOR._options = None
  _SETVOLUMEMESSAGE._serialized_start=107
  _SETVOLUMEMESSAGE._serialized_end=166
# @@protoc_insertion_point(module_scope)
