"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from pyatv.protocols.mrp.protobuf import TransactionPacket_pb2 as _TransactionPacket_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TransactionPackets(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACKETS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def packets(self) -> _containers.RepeatedCompositeFieldContainer[_TransactionPacket_pb2.TransactionPacket]: ...
    def __init__(
        self,
        *,
        packets: _abc.Iterable[_TransactionPacket_pb2.TransactionPacket] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["packets", b"packets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TransactionPackets: _TypeAlias = TransactionPackets  # noqa: Y015
