# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/protocols/mrp/protobuf/TransactionPackets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pyatv.protocols.mrp.protobuf import TransactionPacket_pb2 as pyatv_dot_protocols_dot_mrp_dot_protobuf_dot_TransactionPacket__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5pyatv/protocols/mrp/protobuf/TransactionPackets.proto\x1a\x34pyatv/protocols/mrp/protobuf/TransactionPacket.proto\"9\n\x12TransactionPackets\x12#\n\x07packets\x18\x01 \x03(\x0b\x32\x12.TransactionPacket')



_TRANSACTIONPACKETS = DESCRIPTOR.message_types_by_name['TransactionPackets']
TransactionPackets = _reflection.GeneratedProtocolMessageType('TransactionPackets', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONPACKETS,
  '__module__' : 'pyatv.protocols.mrp.protobuf.TransactionPackets_pb2'
  # @@protoc_insertion_point(class_scope:TransactionPackets)
  })
_sym_db.RegisterMessage(TransactionPackets)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONPACKETS._serialized_start=111
  _TRANSACTIONPACKETS._serialized_end=168
# @@protoc_insertion_point(module_scope)
