# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyatv/protocols/mrp/protobuf/TransactionKey.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pyatv/protocols/mrp/protobuf/TransactionKey.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1pyatv/protocols/mrp/protobuf/TransactionKey.proto\"6\n\x0eTransactionKey\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08userData\x18\x02 \x01(\x0c'
)




_TRANSACTIONKEY = _descriptor.Descriptor(
  name='TransactionKey',
  full_name='TransactionKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='TransactionKey.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userData', full_name='TransactionKey.userData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['TransactionKey'] = _TRANSACTIONKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionKey = _reflection.GeneratedProtocolMessageType('TransactionKey', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONKEY,
  '__module__' : 'pyatv.protocols.mrp.protobuf.TransactionKey_pb2'
  # @@protoc_insertion_point(class_scope:TransactionKey)
  })
_sym_db.RegisterMessage(TransactionKey)


# @@protoc_insertion_point(module_scope)
