"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import extension_dict as _extension_dict
from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as _ProtocolMessage_pb2
from pyatv.protocols.mrp.protobuf import VolumeControlAvailabilityMessage_pb2 as _VolumeControlAvailabilityMessage_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VolumeControlCapabilitiesDidChangeMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CAPABILITIES_FIELD_NUMBER: _builtins.int
    ENDPOINTUID_FIELD_NUMBER: _builtins.int
    OUTPUTDEVICEUID_FIELD_NUMBER: _builtins.int
    endpointUID: _builtins.str
    outputDeviceUID: _builtins.str
    @_builtins.property
    def capabilities(self) -> _VolumeControlAvailabilityMessage_pb2.VolumeControlAvailabilityMessage: ...
    def __init__(
        self,
        *,
        capabilities: _VolumeControlAvailabilityMessage_pb2.VolumeControlAvailabilityMessage | None = ...,
        endpointUID: _builtins.str | None = ...,
        outputDeviceUID: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "endpointUID", b"endpointUID", "outputDeviceUID", b"outputDeviceUID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "endpointUID", b"endpointUID", "outputDeviceUID", b"outputDeviceUID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VolumeControlCapabilitiesDidChangeMessage: _TypeAlias = VolumeControlCapabilitiesDidChangeMessage  # noqa: Y015

VOLUMECONTROLCAPABILITIESDIDCHANGEMESSAGE_FIELD_NUMBER: _builtins.int
volumeControlCapabilitiesDidChangeMessage: _extension_dict._ExtensionFieldDescriptor[_ProtocolMessage_pb2.ProtocolMessage, Global___VolumeControlCapabilitiesDidChangeMessage]
