"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf.internal import extension_dict as _extension_dict
from pyatv.protocols.mrp.protobuf import ProtocolMessage_pb2 as _ProtocolMessage_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VolumeCapabilities(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Enum:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EnumEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VolumeCapabilities._Enum.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        Relative: VolumeCapabilities._Enum.ValueType  # 1
        Absolute: VolumeCapabilities._Enum.ValueType  # 2
        Both: VolumeCapabilities._Enum.ValueType  # 3

    class Enum(_Enum, metaclass=_EnumEnumTypeWrapper):
        """This is really a bitmap but protobuf has no type for that, so lets just add a "Both"
        option since only two values exist anyway
        """

    Relative: VolumeCapabilities.Enum.ValueType  # 1
    Absolute: VolumeCapabilities.Enum.ValueType  # 2
    Both: VolumeCapabilities.Enum.ValueType  # 3

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VolumeCapabilities: _TypeAlias = VolumeCapabilities  # noqa: Y015

@_typing.final
class VolumeControlAvailabilityMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOLUMECONTROLAVAILABLE_FIELD_NUMBER: _builtins.int
    VOLUMECAPABILITIES_FIELD_NUMBER: _builtins.int
    volumeControlAvailable: _builtins.bool
    volumeCapabilities: Global___VolumeCapabilities.Enum.ValueType
    def __init__(
        self,
        *,
        volumeControlAvailable: _builtins.bool | None = ...,
        volumeCapabilities: Global___VolumeCapabilities.Enum.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["volumeCapabilities", b"volumeCapabilities", "volumeControlAvailable", b"volumeControlAvailable"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["volumeCapabilities", b"volumeCapabilities", "volumeControlAvailable", b"volumeControlAvailable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VolumeControlAvailabilityMessage: _TypeAlias = VolumeControlAvailabilityMessage  # noqa: Y015

VOLUMECONTROLAVAILABILITYMESSAGE_FIELD_NUMBER: _builtins.int
volumeControlAvailabilityMessage: _extension_dict._ExtensionFieldDescriptor[_ProtocolMessage_pb2.ProtocolMessage, Global___VolumeControlAvailabilityMessage]
